source 'https://github.com/CocoaPods/Specs.git'

pod 'RestKit', '~> 0.23'
pod 'SVProgressHUD', '~> 1.0'
pod 'PSTAlertController', '~> 1.0'
pod 'Lockbox', '~> 2.1'
pod 'ActionSheetPicker-3.0'
pod 'ReactiveCocoa', '~> 2.4'
pod 'SOMotionDetector', '~> 1.0.1'
pod 'SDWebImage', '~> 3.7'
